### ISSUE TITLE
Readme markdown not rendering the same as GitHub

### ISSUE THREAD

**Issue by nathany** [hstove/issue_stats#13]
Hi. Cool site.

FYI, some of the formatting (tables, links) isn't coming through the way it's on GitHub:

Compare:
http://issuestats.com/github/go-fsnotify/fsnotify
https://github.com/go-fsnotify/fsnotify#file-system-notifications-for-go

**Comment by hstove** [comment]
Thanks for the reports!

@nathany , I switched to a better markdown parser (`marked`) which is faster and deals better with tables. `fsnotify` is looking good now.

@Wilfred , I switched to a better base64 decoder and those unicode issues aren't happening any more.

Thanks again for the bug reports!

**Comment by nathany** [comment]
Thanks. Much better.
