### ISSUE TITLE
style=flat-square is not working

### ISSUE THREAD

**Issue by adamralph** [hstove/issue_stats#16]
Current screenshot from https://github.com/hstove/issue_stats/blob/master/README.md

![image](https://cloud.githubusercontent.com/assets/677704/5719606/41836ac6-9b1a-11e4-92be-fda004712bc4.png)

Indeed, if I navigate to http://issuestats.com/github/joyent/node/badge/pr?style=flat-square then I get forwarded to http://img.shields.io/badge/Pull%20Requests%20Closed%20In-1%20day-green.svg (no style set at all).

**Comment by hstove** [comment]
Works now! 

http://issuestats.com/github/FakeItEasy/FakeItEasy/badge/pr?style=flat-square

![http://issuestats.com/github/FakeItEasy/FakeItEasy/badge/pr?style=flat-square](http://issuestats.com/github/FakeItEasy/FakeItEasy/badge/pr?style=flat-square)

**Comment by adamralph** [comment]
Woot! Thanks very much!
