### ISSUE TITLE
Question: is there an API which can be used by shields.io?

### ISSUE THREAD

**Issue by adamralph** [hstove/issue_stats#17]
I've raised an issue over at https://github.com/badges/shields/issues/351 to support issuestats.

In order to do that, issuestats will have to expose some kind of API which shields.io can use to generate the badge. Does something like this exist? (see https://github.com/badges/shields/issues/351#issuecomment-69879359)

(Allowing shields.io to work for issuestats would mean that issuestats can drop their own badge creation and point to shields.io instead, removing the need to fix things like https://github.com/hstove/issue_stats/issues/16.)

**Comment by hstove** [comment]
There is now! I left a comment on that shields issue.

https://github.com/hstove/issue_stats#api

**Comment by adamralph** [comment]
:+1: great work!
