### ISSUE TITLE
Integration with Github-Time-Tracking?

### ISSUE THREAD

**Issue by StephenOTT** [hstove/issue_stats#18]
Hey

So I am thinking the Time Tracking features of Issue Stats would be a great complementary feature with the current issue stats.

https://github.com/StephenOTT/GitHub-Time-Tracking

Any interest on collaborating on this?

@hstove

**Comment by hstove** [comment]
Sorry, but I don't have time to integrate any new features into issuestats. However, I did somewhat recently put together a [JSON API](https://github.com/hstove/issue_stats#api), if you're interested!
