### ISSUE TITLE
Filter by time period

### ISSUE THREAD

**Issue by sheymann** [hstove/issue_stats#19]
Hello,

I love the information provided by the charts and badge, however it would be much more useful if I could filter by time period, e.g. to spot slowness in the last couple of months.

Also, what is the formula for the badge? Is it the average in the last year or something? It's not clear.

Thanks

**Comment by hstove** [comment]
The formula returned is the median time to close issues/PRs, across all issues and PRs. There is no time frame involved. It's possible to involve time frames, but I don't have the time to implement it. I'd be happy to nudge you the right way if you want to contribute this!
