### ISSUE TITLE
lower-case badge text

### ISSUE THREAD

**Issue by brettwooldridge** [hstove/issue_stats#22]
The standard that has largely emerged is fully lower-cased badges... it would be nice if Issue Stats adopted a similar style.

Issues Closed In → issues closed in

**Comment by hstove** [comment]
I would accept this if someone submitted a PR!

**Comment by hstove** [comment]
JK - just implemented. Badges are now lower case!

**Comment by brettwooldridge** [comment]
Ha, you got me. I was just about to open my fork.
