### ISSUE TITLE
Hyperlinks in README.md are not canonicalized

### ISSUE THREAD

**Issue by LouisTakePILLz** [hstove/issue_stats#29]
Relative links displayed from a repository's `README.md` file will point to the hosting website's current location, as opposed to the source (i.e. github.com).

As a means of example, the following would point to `issuestats.com/github/username/repo/img/logo.png`:
``` md
![Logo](./img/logo.png)
```

Here's one of my affected repositories, where you can clearly see the linked `logo.png` not loading due to broken path mapping: [issuestats.com/github/LouisTakePILLz/ArgumentParser](http://www.issuestats.com/github/LouisTakePILLz/ArgumentParser)

**Comment by hstove** [comment]
Sorry, but I don't see a way to do this with [marked](https://github.com/chjj/marked) (which issuestats uses), so I don't see this being implemented in this project. If you can find a markdown parser with support for this feature, I would be happy to check it out and try and implement it.
