### ISSUE TITLE
[Support] Private Repository

### ISSUE THREAD

**Issue by jspizziri** [hstove/issue_stats#30]
What is the ability to utilize this for a set of private repositories on github? From what I see, it doesn't look like authentication is intended.

**Comment by tomasstrejcek** [comment]
+1

**Comment by jspizziri** [comment]
@hstove, any thoughts on this?

**Comment by hstove** [comment]
I think if this was implemented I'd want to go the route that most other Github integrations go with, which is to have premium (paid) accounts which can use private repositories. @jspizziri @tomasstrejcek would you be interested in something like that?

**Comment by jspizziri** [comment]
I think in general there would be some interest in this, especially if the functionality was enhanced as well.
