### ISSUE TITLE
Flat style badges aren't working

### ISSUE THREAD

**Issue by martellaj** [hstove/issue_stats#34]
Looks like if you add "?style=flat" to the URL that no data gets returned and instead displays "not available". This is confusing because on your website, issuestats.com, the flat badge with data shows when you display the Markdown from the repository's README, but it doesn't work in the GitHub page itself.

**Comment by hstove** [comment]
Do you have an example? It's working, for example, on the [issue_stats README](https://github.com/hstove/issue_stats)

**Comment by martellaj** [comment]
Maybe it fixed itself in the 3 and a half months since I opened the issue. 💁
