### ISSUE TITLE
Should turn image caching off

### ISSUE THREAD

**Issue by ChristopherKing42** [hstove/issue_stats#39]
See https://github.com/github/markup/issues/224#issuecomment-33454537.
Basically, if you don't tell gitHub not to cache your image, it gets out of date.

**Comment by ChristopherKing42** [comment]
Maybe [this line](https://github.com/hstove/issue_stats/commit/5a2e9f916c57bcde6261c0baf3706052a9916f8e#diff-97b4cd6a6c78bf979a5c16e861f345a5L24) shouldn't have been deleted?

**Comment by hstove** [comment]
Adding `expires_now` does that behind the scenes, and then some. That code change is what fixed the image caching issue, discussed here: https://github.com/hstove/issue_stats/issues/20
